name = "ray-wallet"
type = "webpack"
account_id = "792461088a4c863230f3faee467094b1"
# workers_dev = true
route = "raywallet.io/*"
zone_id = "52e500366bb28eae347b932bf92162ca"

[site]
bucket = "../build"
entry-point = "workers-site"
